<?php
/**
 * @package    Bizcity_Twin_AI
 * @subpackage Core\Automation
 * @author     Johnny Chu (Chu Hoàng Anh) <Hoanganh.itm@gmail.com>
 * @copyright  2024-2026 BizCity — Made in Vietnam 🇻🇳
 * @license    GPL-2.0-or-later
 *
 * BizCity_Automation_Installer — table provisioner (BE-1).
 *
 * Idempotent. The actual `CREATE TABLE` SQL is generated by
 * `BizCity_Diagnostics_Auto_Create::run( $suffix )` from the JSON contract
 * `core/diagnostics/changelog/core.automation.json`. This installer just:
 *
 *  - Stamps `bizcity_automation_db_version` option;
 *  - Triggers auto-create for each suffix if either the option is stale OR
 *    a target table is missing (heals manually-dropped tables);
 *  - Exposes a public `ensure()` method for use by REST controllers / probes.
 *
 * NEVER write raw `dbDelta` here — schema source-of-truth is JSON (R-DCL).
 */

defined( 'ABSPATH' ) || exit;

final class BizCity_Automation_Installer {

	const DB_VERSION        = '1.7.0';
	const DB_VERSION_OPTION = 'bizcity_automation_db_version';

	/** Table suffixes (without wp_ prefix) declared in core.automation.json. */
	const TABLE_SUFFIXES = array(
		'bizcity_automation_workflows',
		'bizcity_automation_runs',
		'bizcity_automation_logs',
		'bizcity_automation_templates', // BE-7
	);

	private static bool $checked = false;

	/**
	 * Ensure all automation tables exist + version stamp is current.
	 *
	 * Cheap to call repeatedly:
	 *  - In-process static `$checked` short-circuits within a single request.
	 *  - Once `bizcity_automation_db_version` option == DB_VERSION, we trust
	 *    the stamp and SKIP `SHOW TABLES LIKE` queries. The presence check
	 *    only runs the FIRST time a new DB_VERSION is encountered (or after
	 *    an admin clears the option via diagnostics rerun).
	 *
	 * To force re-verification (e.g. after manual DROP TABLE in dev):
	 *   delete_option( 'bizcity_automation_db_version' );
	 */
	public static function ensure(): void {
		if ( self::$checked ) {
			return;
		}
		self::$checked = true;

		$stamped = get_option( self::DB_VERSION_OPTION, '' );
		if ( $stamped === self::DB_VERSION ) {
			// Trust the stamp — no SHOW TABLES on every request.
			return;
		}
		if ( ! class_exists( 'BizCity_Diagnostics_Auto_Create' ) ) {
			// Auto-create not loaded yet (very early request). Defer to admin_init.
			add_action( 'admin_init', array( __CLASS__, 'ensure_admin_init' ), 1 );
			return;
		}
		// First time at this DB_VERSION → verify + create missing tables.
		foreach ( self::TABLE_SUFFIXES as $suffix ) {
			BizCity_Diagnostics_Auto_Create::run( $suffix );
		}
		if ( self::all_tables_present() ) {
			update_option( self::DB_VERSION_OPTION, self::DB_VERSION, false );
		}
	}

	public static function ensure_admin_init(): void {
		self::$checked = false;
		self::ensure();
	}

	public static function all_tables_present(): bool {
		global $wpdb;
		foreach ( self::TABLE_SUFFIXES as $suffix ) {
			$full = $wpdb->prefix . $suffix;
			$exists = $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $full ) );
			if ( $exists !== $full ) {
				return false;
			}
		}
		return true;
	}

	public static function table( string $suffix ): string {
		global $wpdb;
		return $wpdb->prefix . $suffix;
	}
}
