<?php
/**
 * @package    Bizcity_Twin_AI
 * @subpackage Core\Automation
 * @author     Johnny Chu (Chu Hoàng Anh) <Hoanganh.itm@gmail.com>
 * @copyright  2024-2026 BizCity — Made in Vietnam 🇻🇳
 * @license    GPL-2.0-or-later
 *
 * BizCity_Automation_Installer — table provisioner (BE-1).
 *
 * Idempotent. The actual `CREATE TABLE` SQL is generated by
 * `BizCity_Diagnostics_Auto_Create::run( $suffix )` from the JSON contract
 * `core/diagnostics/changelog/core.automation.json`. This installer just:
 *
 *  - Stamps `bizcity_automation_db_version` option;
 *  - Triggers auto-create for each suffix if either the option is stale OR
 *    a target table is missing (heals manually-dropped tables);
 *  - Exposes a public `ensure()` method for use by REST controllers / probes.
 *
 * NEVER write raw `dbDelta` here — schema source-of-truth is JSON (R-DCL).
 */

defined( 'ABSPATH' ) || exit;

final class BizCity_Automation_Installer {

	const DB_VERSION        = '1.7.0';
	const DB_VERSION_OPTION = 'bizcity_automation_db_version';

	/** Table suffixes (without wp_ prefix) declared in core.automation.json. */
	const TABLE_SUFFIXES = array(
		'bizcity_automation_workflows',
		'bizcity_automation_runs',
		'bizcity_automation_logs',
		'bizcity_automation_templates', // BE-7
	);

	// [2026-06-13 Johnny Chu] HOTFIX — per-blog guard array so switch_to_blog() in multisite cron
	// does not skip ensure() for sub-blogs whose tables were never provisioned.
	private static $checked_blog_ids = array();

	// [2026-06-21 Johnny Chu] HOTFIX — per-blog per-request SHOW TABLES cache.
	// Avoids N×SHOW-TABLES on every cron tick for blogs that DO have tables.
	private static $tables_present_cache = array();

	/**
	 * Check workflows table existence once per blog per request.
	 * Result cached in static property — safe to call from every cron hook.
	 */
	public static function tables_present_cached(): bool {
		$blog_id = (int) get_current_blog_id();
		if ( ! array_key_exists( $blog_id, self::$tables_present_cache ) ) {
			global $wpdb;
			$tbl = $wpdb->prefix . 'bizcity_automation_workflows';
			self::$tables_present_cache[ $blog_id ] = bizcity_tbl_exists( $tbl ); // [2026-06-21 Johnny Chu] R-SHOW-TABLES
		}
		return self::$tables_present_cache[ $blog_id ];
	}

	/** Invalidate tables_present_cached() for current blog (call after ensure/install). */
	public static function invalidate_tables_cache(): void {
		$blog_id = (int) get_current_blog_id();
		unset( self::$tables_present_cache[ $blog_id ] );
	}

	/**
	 * Ensure all automation tables exist + version stamp is current.
	 *
	 * Cheap to call repeatedly:
	 *  - Static `$checked` short-circuits within a single request.
	 *  - Once `bizcity_automation_db_version` option == DB_VERSION, we trust
	 *    the stamp and SKIP `SHOW TABLES LIKE` queries. The presence check
	 *    only runs the FIRST time a new DB_VERSION is encountered (or after
	 *    an admin clears the option via diagnostics rerun).
	 *
	 * To force re-verification (e.g. after manual DROP TABLE in dev):
	 *   delete_option( 'bizcity_automation_db_version' );
	 */
	public static function ensure(): void {
		$blog_id = (int) get_current_blog_id();
		if ( isset( self::$checked_blog_ids[ $blog_id ] ) ) {
			return;
		}
		self::$checked_blog_ids[ $blog_id ] = true;

		$stamped = get_option( self::DB_VERSION_OPTION, '' );
		if ( $stamped === self::DB_VERSION ) {
			// Trust the stamp — no SHOW TABLES on every request.
			return;
		}
		if ( ! class_exists( 'BizCity_Diagnostics_Auto_Create' ) ) {
			// [2026-06-21 Johnny Chu] HOTFIX — In cron context admin_init never fires.
			// If the diagnostics bootstrap is already loaded (BIZCITY_DIAGNOSTICS_DIR defined),
			// require the two auto-create files directly instead of deferring uselessly.
			if ( defined( 'BIZCITY_DIAGNOSTICS_DIR' ) ) {
				if ( ! class_exists( 'BizCity_Diagnostics_Changelog_Loader' ) ) {
					require_once BIZCITY_DIAGNOSTICS_DIR . 'includes/class-diagnostics-changelog-loader.php';
				}
				require_once BIZCITY_DIAGNOSTICS_DIR . 'includes/class-diagnostics-auto-create.php';
			} else {
				// Auto-create not loaded yet (very early request). Defer to admin_init.
				add_action( 'admin_init', array( __CLASS__, 'ensure_admin_init' ), 1 );
				return;
			}
		}
		// First time at this DB_VERSION → verify + create missing tables.
		foreach ( self::TABLE_SUFFIXES as $suffix ) {
			BizCity_Diagnostics_Auto_Create::run( $suffix );
		}
		if ( self::all_tables_present() ) {
			update_option( self::DB_VERSION_OPTION, self::DB_VERSION, false );
			self::invalidate_tables_cache(); // [2026-06-21 Johnny Chu] HOTFIX — refresh after install
		}
	}

	public static function ensure_admin_init(): void {
		$blog_id = (int) get_current_blog_id();
		unset( self::$checked_blog_ids[ $blog_id ] ); // reset so ensure() re-verifies for this blog
		self::ensure();
	}

	public static function all_tables_present(): bool {
		global $wpdb;
		foreach ( self::TABLE_SUFFIXES as $suffix ) {
			$full = $wpdb->prefix . $suffix;
			if ( ! bizcity_tbl_exists( $full ) ) { // [2026-06-21 Johnny Chu] R-SHOW-TABLES
				return false;
			}
		}
		return true;
	}

	public static function table( string $suffix ): string {
		global $wpdb;
		return $wpdb->prefix . $suffix;
	}
}
